### ISSUE TITLE
ldhname not rfcconform?

### ISSUE THREAD

**Issue by mortensen** [DNSBelgium/rdap#15]
Your implementation generates something like this:
`"ldhName": {
    "labels": [
      {
        "stringValue": "test"
      },
      {
        "stringValue": "de"
      }
    ],
    "tldlabel": {
      "stringValue": "de"
    },
    "levelSize": 2,
    "fqdn": false,
    "stringValue": "test.de"
  },`

The RFC 7483 says:
`
"ldhName" : "ns1.xn--fo-5ja.example",
`

Is your implementation not rfc conform? Or can you tell me why there is a difference? 

Thanks in advance for your feedback.

**Comment by mortensen** [comment]
And what about notices \ type ? Also not in RFC 7483?

**Comment by darkmanneke** [comment]
Are you using be.dnsbelgium.rdap.WebConfig?
See the readme: you need to do an import: @Import(be.dnsbelgium.rdap.WebConfig.class)  

Or if you do the configuration differently: make sure to customize the ObjectMapper, see converter() and getObjectMapper() methods in WebConfig.

The json output of the rdap server should look like the json files in the server/src/test/resources dir

**Comment by mortensen** [comment]
We were using the WebMVC annotation from spring which collided with your configuration. After removing this annotation it works in your way. This ticket can be closed. Thanks
