### ISSUE TITLE
Support for contact uri

### ISSUE THREAD

**Issue by mortensen** [DNSBelgium/rdap#19]
https://www.icann.org/en/system/files/files/rdap-response-profile-15feb19-en.pdf

2.7.5.
Email –
2.7.5.2.Email (Registrar Only) - the value of the CONTACT-URI member in the entity object of the RDAP response MUST be an emailaddress or link to a web form.

CONTACT-URI
https://tools.ietf.org/html/rfc8605

The CONTACT-URI property can be used to include URIs representing an email address or a location for a web form.

https://tools.ietf.org/html/rfc7480#section-9
9.1. URIs and IRIs
Clients can use Internationalized Resource Identifiers (IRIs)
[RFC3987] for internal use as they see fit but MUST transform them to
URIs [RFC3986] for interaction with RDAP servers. RDAP servers MUST
use URIs in all responses, and again clients can transform these URIs
to IRIs for internal use as they see fit.
RDAP servers MUST use URIs in all responses

**Comment by mortensen** [comment]
please assign this ticket to me.

**Comment by mortensen** [comment]
I created a pull request. Please check and confirm, if possible. Thanks

**Comment by darkmanneke** [comment]
I've merged the pull request. Thanks for your contribution.

**Comment by mortensen** [comment]
@darkmanneke Thanks for the merge! Is there a chance for a soon release? We could use the new version and would like to deploy it to our live servers. Regards

**Comment by mortensen** [comment]
Any new infos about a possible release maybe? Thanks.

**Comment by Kent1** [comment]
It has been released. See https://mvnrepository.com/artifact/be.dnsbelgium/rdap-core/2.0.10

**Comment by mortensen** [comment]
Thanks for that!
